name: Multi-Repo Pipeline Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_repo1:
    runs-on: self-hosted
    steps:
    - name: Checkout Microservices
      uses: actions/checkout@v4
      with:
        repository: Hieuln99/Microservices  # Thay 'user/repo1' bằng tên repo đầu tiên
        token: ${{ secrets.GITHUB_TOKEN }}  # Dùng GitHub token để có quyền truy cập
        ref: main  # Chỉ định nhánh cần checkout từ repo1

    - name: Upload Repo1 Source as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo1-source
        path: .  # Tải toàn bộ mã nguồn từ repo1

  build_repo2:
    runs-on: self-hosted
    steps:
    - name: Checkout TestHTML
      uses: actions/checkout@v4
      with:
        repository: Hieuln99/TestHTML  # Thay 'user/repo2' bằng tên repo thứ hai
        token: ${{ secrets.GITHUB_TOKEN }}  # Dùng GitHub token để có quyền truy cập
        ref: main  # Chỉ định nhánh cần checkout từ repo2

    - name: Upload Repo2 Source as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo2-source
        path: .  # Tải toàn bộ mã nguồn từ repo2

  build:
    needs: [build_repo1, build_repo2]  # Đảm bảo job này chỉ chạy sau khi cả hai job trên hoàn tất
    runs-on: self-hosted

    steps:
    - name: Download Repo1 Source
      uses: actions/download-artifact@v3
      with:
        name: repo1-source  # Tải artifact từ job build_repo1
        path: ./repo1  # Lưu vào thư mục repo1

    - name: Download Repo2 Source
      uses: actions/download-artifact@v3
      with:
        name: repo2-source  # Tải artifact từ job build_repo2
        path: ./repo2  # Lưu vào thư mục repo2

    - name: Print Repositories' Content
      run: |
        echo "Content of Repo1:"
        ls ./repo1
        echo "Content of Repo2:"
        ls ./repo2

    - name: Checkout Main Project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath "GitHubActionsWorkflow.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Create the app package
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    - name: Remove the pfx
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
